### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [xaraya/core#61]
Dear @xaraya team, @random777, @mrvdb, @mikespub, @paramss, @godboko, @rolfmeijer, @CaraesNaur, @psspl1998, @ano7, @developweb10, @ftb,

It is possible to migrate the personal account to organization?

There was a previous ticket but one guy has closed it without solution:
- https://github.com/xaraya/core/issues/59

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by mikespub** [comment]
Sorry @Neustradamus given your request I simply didn't understand what you are trying to achieve, so I assumed it was some kind of bot.

FYI the Xaraya core and Xaraya module code have only ever been hosted on Sourceforge as a **copy** since its inception. The main code repositories were migrated to Github almost 15 years ago from the previous cvs, monotone, bitkeeper etc. source code management tools, and there are no plans to update or close the Sourceforge repos - assuming anyone from the original team still even has admin access to them.

I do not own the Xaraya personal account, but given the infrequent updates to the repositories I doubt he has any interest in turning it into an organization at this point...

**Comment by Neustradamus** [comment]
@mikespub: Please do not close an unsolved ticket, please reopen.

Who has rights on the xaraya personal account?
What is the email address linked?
Who has added you some rights on this repository?

Thanks in advance.
